name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  update-index:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Install deps
        run: pnpm i
      
      - name: Lint code
        run: pnpm lint
      
      - name: Execute tests
        run: pnpm test